version: '3'
services:
  db:
    image: postgres:15.3-alpine3.18
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./schema:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python app.py
    volumes:
      - ./www:/www
    ports:
      - "5050:5050"
    depends_on:
      - db
